export enum VAR {
  TITLE_MIN_LENGTH = 3,
  TITLE_MAX_LENGTH = 64,
  DESCRIPTION_MIN_LENGTH = 10,
  DESCRIPTION_MAX_LENGTH = 255,
  QUESTION_MIN_LENGTH=1,
  QUESTION_MAX_LENGTH=128,
  OPTION_MIN_LENGTH=1,
  OPTION_MAX_LENGTH=64,
  ANSWERS_VALUE_MIN_LENGTH=1,
  ANSWERS_VALUE_MAX_LENGTH=255
}